// Auto-generated by Base44 CLI - DO NOT EDIT
// Regenerate with: base44 types generate

export interface User {
  /**
   * The role of the user in the app
   */
  role: "admin" | "user";
  player_provision_key?: string;
  player_provision_status?: "pending" | "working" | "complete";
  player_provision_token?: string;
  player_provision_claimed_at?: string;
  daily_quest_provision_key?: string;
  daily_quest_provision_status?: "pending" | "working" | "complete";
  daily_quest_provision_token?: string;
  daily_quest_provision_claimed_at?: string;
  weekly_quest_provision_key?: string;
  weekly_quest_provision_status?: "pending" | "working" | "complete";
  weekly_quest_provision_token?: string;
  weekly_quest_provision_claimed_at?: string;
  league_provision_key?: string;
  league_provision_status?: "pending" | "working" | "complete";
  league_provision_token?: string;
  league_provision_claimed_at?: string;
}

export interface AchievementUnlock {
  user_id: string;
  achievement_key: string;
  title: string;
  unlocked_at: string;
}

export interface CupBracket {
  season_id: string;
  division: string;
  cohort: number;
  round: number;
  slot: number;
  player_one_id?: string;
  player_two_id?: string;
  match_id?: string;
  winner_user_id?: string;
  player_one_checked_in: boolean;
  player_two_checked_in: boolean;
  status: "pending" | "check_in" | "active" | "complete";
  check_in_at: string;
  activation_status?: "pending" | "working" | "complete";
  advancement_status?: "pending" | "working" | "complete";
}

export interface DuelBotState {
  match_id: string;
  participant_id: string;
  persona_key: string;
  handle: string;
  avatar_seed: string;
  division: string;
  rating: number;
  will_solve: boolean;
  target_guesses: number;
  schedule_ms: number[];
}

export interface DuelMatch {
  kind: "ranked" | "private" | "cup";
  status: "waiting" | "lobby" | "countdown" | "active" | "complete" | "cancelled";
  invite_code?: string;
  player_one_id: string;
  player_two_id?: string;
  winner_user_id?: string;
  session_one_id?: string;
  session_two_id?: string;
  started_at?: string;
  deadline?: string;
  fallback_at?: string;
  countdown_ends_at?: string;
  version: number;
  season_id?: string;
  bracket_id?: string;
  setup_status?: "pending" | "working" | "complete";
  settlement_status?: "pending" | "working" | "complete";
}

export interface DuelParticipant {
  match_id: string;
  user_id: string;
  handle: string;
  avatar_seed?: string;
  guesses_used: number;
  status: "ready" | "playing" | "won" | "lost" | "forfeit";
  controller?: "human" | "bot";
  live_state?:
    | "lobby"
    | "ready"
    | "thinking"
    | "typing"
    | "checking"
    | "locked_in"
    | "solved"
    | "finished"
    | "reconnecting";
  persona_key?: string;
  division?: string;
  departed_user_id?: string;
  connection_lost_at?: string;
  next_update_at?: string;
  elapsed_ms?: number;
  rating_before: number;
  rating_change: number;
  reward_xp?: number;
  reward_tokens?: number;
  league_points?: number;
  last_seen_at: string;
  applied_operation_keys?: string[];
}

export interface GameSession {
  owner_user_id?: string;
  match_id?: string;
  party_room_id?: string;
  guest: boolean;
  mode: "daily" | "endless" | "rush" | "duel" | "party";
  puzzle_key: string;
  puzzle_number: number;
  status: "playing" | "won" | "lost" | "expired" | "forfeit";
  guesses_used: number;
  max_guesses: number;
  round_number: number;
  score: number;
  solved_words: number;
  hard_mode: boolean;
  reward_settled: boolean;
  started_at: string;
  deadline?: string;
  completed_at?: string;
  version: number;
  last_request_id?: string;
  last_request_result?: {};
}

export interface GuessAttempt {
  session_id: string;
  owner_user_id?: string;
  round_number: number;
  sequence: number;
  word: string;
  evaluation: string[];
  request_id: string;
  submitted_at: string;
}

export interface LeaderboardEntry {
  season_id: string;
  user_id: string;
  handle: string;
  division: string;
  cohort: number;
  points: number;
  wins: number;
  rank: number;
  updated_at: string;
  applied_operation_keys?: string[];
}

export interface LeagueMembership {
  season_id: string;
  user_id: string;
  handle: string;
  division: "bronze" | "silver" | "gold" | "platinum" | "diamond";
  cohort: number;
  league_points: number;
  duel_rating: number;
  rank: number;
  cup_qualified: boolean;
  applied_operation_keys?: string[];
}

export interface PartyBotState {
  room_id: string;
  participant_id: string;
  round_number: number;
  will_solve: boolean;
  target_guesses: number;
  schedule_ms: number[];
}

export interface PartyParticipant {
  room_id: string;
  user_id: string;
  viewer_user_ids: string[];
  handle: string;
  avatar_seed?: string;
  controller: "human" | "bot";
  ready: boolean;
  status: "lobby" | "playing" | "solved" | "finished" | "forfeit";
  live_state: "lobby" | "ready" | "thinking" | "typing" | "checking" | "solved" | "finished" | "reconnecting";
  current_session_id?: string;
  progress_rows?: string[];
  round_score: number;
  total_score: number;
  rounds_solved: number;
  round_wins: number;
  guesses_used: number;
  total_guesses: number;
  elapsed_ms: number;
  total_elapsed_ms: number;
  rank: number;
  round_results?: {}[];
  last_seen_at: string;
}

export interface PartyRecap {
  room_id: string;
  viewer_user_ids: string[];
  headline: string;
  summary: string;
  mvp: string;
  coaching_tip: string;
  generated_at: string;
  ai_generated: boolean;
}

export interface PartyRoom {
  invite_code: string;
  host_user_id: string;
  member_user_ids: string[];
  status: "lobby" | "countdown" | "active" | "between_rounds" | "complete" | "cancelled";
  demo: boolean;
  round_number: number;
  round_count: number;
  countdown_ends_at?: string;
  deadline?: string;
  transition_ends_at?: string;
  version: number;
  setup_status: "pending" | "working" | "complete";
  settlement_status: "pending" | "working" | "complete";
  recap_status: "pending" | "working" | "complete" | "fallback";
  last_activity_at: string;
  completed_words?: string[];
}

export interface PlayerAccount {
  user_id: string;
  xp_total: number;
  token_balance: number;
  wallet_version: number;
  current_streak: number;
  max_streak: number;
  last_daily_key?: string;
  streak_shields: number;
  daily_counters?: {};
  settings?: {};
  last_operation_key?: string;
  last_operation_result?: {};
  last_operation_reason?: string;
  last_operation_reference_id?: string;
  last_operation_delivered?: boolean;
  last_utility_operation?: string;
  daily_session_key?: string;
  daily_session_id?: string;
  applied_operation_keys?: string[];
}

export interface PlayerInventory {
  user_id: string;
  item_key: string;
  item_type: "cosmetic" | "utility" | "badge";
  quantity: number;
  acquired_at: string;
}

export interface PlayerProfile {
  user_id: string;
  handle: string;
  avatar_seed: string;
  avatar_url?: string;
  rename_count?: number;
  level: number;
  equipped_cosmetic?: string;
  peak_division: "bronze" | "silver" | "gold" | "platinum" | "diamond";
  games_played: number;
  games_won: number;
  achievements?: string[];
  applied_operation_keys?: string[];
}

export interface PlayerQuest {
  user_id: string;
  period_key: string;
  quest_key: string;
  title: string;
  target: number;
  progress: number;
  reward_tokens: number;
  claimed: boolean;
  rerolled: boolean;
  applied_operation_keys?: string[];
}

export interface PuzzleSecret {
  session_id: string;
  round_number: number;
  answer: string;
}

export interface Season {
  key: string;
  name: string;
  status: "upcoming" | "active" | "cup" | "complete";
  starts_at: string;
  league_ends_at: string;
  ends_at: string;
}

export interface WalletTransaction {
  user_id: string;
  operation_key: string;
  reason: string;
  delta: number;
  xp?: number;
  resulting_balance: number;
  resulting_level?: number;
  reference_id?: string;
  delivery_status?: "pending" | "delivering" | "complete";
}

export interface WordInsight {
  word: string;
  part_of_speech: string;
  pronunciation: string;
  definition: string;
  example: string;
  origin: string;
  usage_note: string;
  generated_at: string;
  schema_version: number;
}

export interface WordlePlayerState {
  /**
   * Owner ID for imported legacy records
   */
  user_id?: string;
  /**
   * Client state schema version
   */
  state_version: number;
  /**
   * Merged settings and per-puzzle progress
   */
  payload: {};
}

declare module '@base44/sdk' {
  interface EntityTypeRegistry {
    "User": User;
    "AchievementUnlock": AchievementUnlock;
    "CupBracket": CupBracket;
    "DuelBotState": DuelBotState;
    "DuelMatch": DuelMatch;
    "DuelParticipant": DuelParticipant;
    "GameSession": GameSession;
    "GuessAttempt": GuessAttempt;
    "LeaderboardEntry": LeaderboardEntry;
    "LeagueMembership": LeagueMembership;
    "PartyBotState": PartyBotState;
    "PartyParticipant": PartyParticipant;
    "PartyRecap": PartyRecap;
    "PartyRoom": PartyRoom;
    "PlayerAccount": PlayerAccount;
    "PlayerInventory": PlayerInventory;
    "PlayerProfile": PlayerProfile;
    "PlayerQuest": PlayerQuest;
    "PuzzleSecret": PuzzleSecret;
    "Season": Season;
    "WalletTransaction": WalletTransaction;
    "WordInsight": WordInsight;
    "WordlePlayerState": WordlePlayerState;
  }
  
  interface FunctionNameRegistry {
    "duel/current": true;
    "economy/purchase": true;
    "duel/create-private": true;
    "duel/forfeit": true;
    "account/delete": true;
    "duel/presence": true;
    "duel/queue": true;
    "duel/join-private": true;
    "duel/status": true;
    "admin/repair-data": true;
    "admin/reset-demo": true;
    "game/bootstrap": true;
    "game/claim-guest": true;
    "game/buy-extra-guess": true;
    "game/guess": true;
    "game/status": true;
    "quests/claim": true;
    "game/word-details": true;
    "game/start": true;
    "quests/reroll": true;
    "profile/update": true;
    "party/create": true;
    "legacy/import": true;
    "party/ready": true;
    "party/join": true;
    "party/recap": true;
    "party/presence": true;
    "party/leave": true;
    "party/status": true;
    "tournament/check-in": true;
    "party/start": true;
    "tournament/enroll": true;
    "tournament/status": true;
  }
}